services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: mini_transmit_nestjs_app_dev
    env_file: .env
    ports:
      - "${NESTJS_PORT}:3001"
    volumes:
      - ./:/app
      - /app/node_modules
   