# 当前test文件用于测试项目build后在本地的运行情况
FROM node:18-alpine

WORKDIR /app

# 使用非root用户运行（使用动态GID）
RUN addgroup -S app && \
    adduser -S -G app -s /bin/sh app

# 复制package.json和package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制应用代码
COPY . .

# 构建应用
RUN npm run build

# 将所有权限授予app用户
RUN chown -R app:app /app

# 切换到app用户
USER app


# 暴露端口
EXPOSE 3000

# 启动生产服务器
CMD ["node", "dist/main"] 