services:
  app:
    image: ${DOCKER_USERNAME}/mini_transmit_nestjs:latest
    container_name: mini_transmit_nestjs_app_prod
    env_file: .env
    ports:
      - "${NESTJS_PORT}:3001"
    restart: unless-stopped
   



